<div class="blog-section">
    <h2>Blog</h2>
    
    <div class="blog-posts">
        <article class="blog-post">
            <h3><a href="#post1">Understanding Web Security Fundamentals</a></h3>
            <p class="post-meta">January 15, 2024 | Security, Web Development</p>
            <p class="post-excerpt">
                Exploring common web vulnerabilities and how to protect against them. 
                This post covers the basics of XSS, SQL injection, and CSRF attacks with practical examples.
            </p>
            <a href="#post1" class="read-more">Read More →</a>
        </article>
        
        <article class="blog-post">
            <h3><a href="#post2">PHP Security Best Practices</a></h3>
            <p class="post-meta">January 10, 2024 | PHP, Security</p>
            <p class="post-excerpt">
                A comprehensive guide to secure PHP development practices. Learn about input validation, 
                output encoding, and secure configuration settings that every PHP developer should know.
            </p>
            <a href="#post2" class="read-more">Read More →</a>
        </article>
        
        <article class="blog-post">
            <h3><a href="#post3">CTF Competition Writeups</a></h3>
            <p class="post-meta">January 5, 2024 | CTF, Hacking</p>
            <p class="post-excerpt">
                Detailed writeups from recent CTF competitions including web challenges, 
                cryptography puzzles, and reverse engineering tasks. Solutions and methodologies explained.
            </p>
            <a href="#post3" class="read-more">Read More →</a>
        </article>
        
        <article class="blog-post">
            <h3><a href="#post4">Building Secure Applications</a></h3>
            <p class="post-meta">December 28, 2023 | Development, Security</p>
            <p class="post-excerpt">
                From design to deployment, learn how to build applications with security in mind. 
                This post covers threat modeling, secure coding practices, and security testing.
            </p>
            <a href="#post4" class="read-more">Read More →</a>
        </article>
    </div>
</div>
<div class="ai-notice" style="text-align:center;margin-top:2rem;color:#888;">Contents are generated by AI.</div> 