<div class="contacts-section">
    <h2>Contacts</h2>
    
    <div class="contact-content">
        <div class="contact-info">
            <h3>Get In Touch</h3>
            <p>Feel free to reach out for collaboration, questions, or just to say hello!</p>
            
            <div class="contact-methods">
                <div class="contact-item">
                    <strong>Email:</strong> 
                    <a href="mailto:5020559@gmail.com">5020559@gmail.com</a>
                </div>
                
                <div class="contact-item">
                    <strong>GitHub:</strong> 
                    <a href="https://github.com/Vincent550102" target="_blank">Vincent550102</a>
                </div>
                
                <div class="contact-item">
                    <strong>LinkedIn:</strong> 
                    <a href="https://www.linkedin.com/in/vincent-yang-8291a51b4/" target="_blank">Vincent Yang
                    </a>
                </div>
                
            </div>
        </div>
    </div>
</div>
<div class="ai-notice" style="text-align:center;margin-top:2rem;color:#888;">Contents are generated by AI.</div> 